package vocibilancio;
/**
 * Classe enum per la definizione delle voci di bilancio
 * 
 * @author Matteo
 *
 */
public enum VociBilancioContoEconomico {
	/*
	 * Vengono aggiunti tre spazi per identazione dei sottogruppi
	 */
	A("A-VALORE DELLA PRODUZIONE"),
	AI("   I-RICAVI DELLE VENDITE E DELLE PRESTAZIONI"),
	AII("   II-VARIAZIONI DELLE RIMANENZE DI PRODOTTI IN CORSO DI LAVORAZIONE, SEMILAVORATI E FINITI"),
	AIII("   III-VARIAZIONE DEI LAVORI IN CORSO DI ORDINAZIONE"),
	AIV("   IV-INCREMENTI DI IMMOBILIZZAZIONI PER LAVORI INTERNI"),
	AV("   V-ALTRI RICAVI E PROVENTI"),
	B("B-COSTI DELLA PRODUZIONE"),
	BI("   I-PER MATERIE PRIME, SUSSIDIARIE, DI CONSUMO E MERCI"),
	BII("   II-PER SERVIZI"),
	BIII("   III-PER GODIMENTO DI BENI DI TERZI"),
	BIV("   IV-PER IL PERSONALE"),
	BIVA("      a)SALARI E STIPENDI"),
	BIVB("      b)ONERI SPECIALE"),
	BIVC("      c)TRATTAMENTO DI FINE RAPPORTO"),
	BIVD("      d)TRATTAMENTO DI QUIESCENZA E SIMILI"),
	BIVE("      e)ALTRI COSTI"),
	BV("   V-AMMORTAMENTI E SVALUTAZIONI"),
	BVA("      a)AMMORTAMENTO DELLE IMMOBILIZZAZIONI IMMATERIALI"),
	BVB("      b)AMMORTAMENTO DELLE IMMOBILIZZAZIONI MATERIALI"),
	BVC("      c)ALTRE SVALUTAZIONI DELLE IMMOBILIZZAZIONI"),
	BVD("      d)SVALUTAZIONE DEI CREDITI COMPRESI NELL'ATTIVO CIRCOLANTE"),
	BVI("   VI-VARIAZIONE DELLE RIMANENZE DI MATERIE PRIME, SUSSIDIARIE, DI CONSUMO E MERCI"),
	BVII("   VII-ACCANTONAMENTO PER RISCHI"),
	BVIII("   VIII-ALTRI ACCANTONAMENTI"),
	BIX("   IX-ONERI DIVERSI DI GESTIONI"),
	C("C-PROVENTI E ONERI FINANZIARI"),
	CI("   I- PROVENTI DA PARTECIPAZIONI"),
	CII("   II-ALTRI PROVENTI FINANZIARI"),
	CIIA("      a)DA CREDITI ISCRITTI NELLE IMMOBILIZZAZIONI"),
	CIIB("      b)DA TITOLI ISCRITTI NELLE IMMOBILIZZAZIONI"),
	CIIC("      c)DA TITOLI ISCRITTI NELL'ATTIVO CIRCOLANTE"),
	CIID("      d)DA PROVENTI DIVERSI DAI PRECEDENTI"),
	CIII("   III-INTERESSI E ALTRI ONERI FINANZIARI"),
	D("D-RETTIFICHE DI VALORE DI ATTIVITA' FINANZIARIE"),
	DI("   I-RIVALUTAZIONI"),
	DIA("      a)Rivalutazioni DI PARTECIPAZIONI"),
	DIB("      b)Rivalutazioni DI IMMOBILIZZAZIONI FINANZIARIE"),
	DIC("      c)Rivalutazioni DI TITOLI ISCRITTI NELL'ATTIVO CIRCOLANTE"),
	DII("   II-SVALUTAZIONI"),
	DIIA("      a)Svalutazioni DI PARTECIPAZIONI"),
	DIIB("      b)Svalutazioni DI IMMOBILIZZAZIONI FINANZIARIE"),
	DIIC("      c)Svalutazioni DI TITOLI ISCRITTI NELL'ATTIVO CIRCOLANTE");
	
	private String nome;
	private VociBilancioContoEconomico(String nome) {
		this.nome = nome;
	}
	
	@Override
	public String toString() {
		return nome;
	}
}
